name: Daily Adhkar

on:
  schedule:
    - cron: '0 3 * * *'  # 6 صباحًا (UTC+3)
    - cron: '0 15 * * *'  # 6 مساءً (UTC+3)

jobs:
  send-adhkar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - run: pip install requests
      
      - run: python send_adhkar.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
