name: Send Telegram Adhkar

on:
  schedule:
    - cron: '0 22 * * *' # UTC 22 = 12am Libya
  workflow_dispatch:

jobs:
  send-adhkar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python send_adhkar.py
