name: Send Telegram Images Libya Time

on:
  schedule:
    # 6 AM Libya (UTC+2) -> 4 AM UTC
    - cron: '0 4 * * *'
    # 6 PM Libya (UTC+2) -> 4 PM UTC
    - cron: '0 16 * * *'

jobs:
  send-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine image
        id: set-image
        run: |
          if [ $(date -u +%H) -eq 4 ]; then
            echo "IMAGE_PATH=morning.jpg" >> $GITHUB_ENV
          elif [ $(date -u +%H) -eq 16 ]; then
            echo "IMAGE_PATH=evening.jpg" >> $GITHUB_ENV
          fi

      - name: Send to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          photo: ${{ env.IMAGE_PATH }}
